# Generated by Django 2.1 on 2018-08-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='add_time',
            new_name='password',
        ),
    ]
